name: Build and deploy

on:
  push:
    branches: [ master ]
    
  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: npm install -g firebase-tools
    - name: yarn install, build and test
      run: |
        yarn install
        yarn run build
        ls build/
        sed -i "s/\/github-basics-prushothman//g" build/index.html
        firebase deploy --token "1//0g08WuWEkpbn7CgYIARAAGBASNwF-L9IrngZsyVpfAsIWsgT0tS10tiKlGP05_Emw5wsVMZ22vBhr5nF6WjWG0kYPYhkKd3TQ56A" --project "burgerapp-fec0e"
    # - name: Archive Build
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: dist
    #       path: dist


